### ISSUE TITLE
运行LLM4RObot报错

### ISSUE THREAD

**Issue by lqx-sdu** [lake1115/LLM4Robot#2]
无论下载main分支还是ks分支，在按照readme配置后，运行main的时候都会产生如下报错，请问这是哪里有问题吗？
(llm4robot) lqx@lqx-ThinkStation-P360-Tower:~/LLM4Robot$ python main.py train --save_name "experiment1" 
/home/lqx/LLM4Robot/habitat_env.py:66: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  hydra.initialize(config_path=config_path, job_name=f"{args.eval_type}")
2024-12-19 09:48:22,856 Initializing dataset RearrangeDataset-v0
2024-12-19 09:48:22,858 initializing sim RearrangeSim-v0
Traceback (most recent call last):
  File "/home/lqx/LLM4Robot/main.py", line 55, in <module>
    env = Env(args)
  File "/home/lqx/LLM4Robot/habitat_env.py", line 69, in __init__
    self.env = habitat.gym.make_gym_from_config(self.config)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/gym/gym_definitions.py", line 61, in make_gym_from_config
    return make_env_fn(env_class=env_class, config=config)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/utils/env_utils.py", line 33, in make_env_fn
    env = env_class(config=config, dataset=dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/environments.py", line 126, in __init__
    base_env = RLTaskEnv(config=config, dataset=dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/environments.py", line 46, in __init__
    super().__init__(config, dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/env.py", line 382, in __init__
    self._env = Env(config, dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/env.py", line 114, in __init__
    self._sim = make_sim(
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/tasks/rearrange/rearrange_sim.py", line 80, in __init__
    super().__init__(config)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/sims/habitat_simulator/habitat_simulator.py", line 292, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/sims/habitat_simulator/habitat_simulator.py", line 352, in create_sim_config
    sim_config.navmesh_settings = habitat_sim.nav.NavMeshSettings()
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'navmesh_settings'
Exception ignored in: <function Simulator.__del__ at 0x74f0ed15bdc0>
Traceback (most recent call last):
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 571, in __del__
    self.close(destroy=True)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 132, in close
    if not self._initialized:
AttributeError: 'RearrangeSim' object has no attribute '_initialized'

**Comment by lake1115** [comment]
看起来像是habitat运行有问题，请问配置好之后测试的example.py能成功运行吗？

**Comment by lqx-sdu** [comment]
examply.py也会出现一样的报错，目前看来好像是官网目前可下载的habitat-sim-0.2.4版本和您代码里habitat-lab-0.2.4版本不匹配导致的。我如果从官网下载并安装habitat-sim-0.2.4以及habitat-lab-0.2.4是可以运行examply.py，但是官网下载的habitat-lab-0.2.4缺少您对于habitat-lab的改动，少很多文件和修改，所以现在还是无法跑这个代码。

**Comment by lake1115** [comment]
可以贴一下运行example.py的报错吗？有可能是读取地图的链接没弄对。当然也可以以你能运行的habitat环境为基础，对照改动查看

**Comment by lqx-sdu** [comment]
这个是运行example.py的报错：
(llm4robot) lqx@lqx-ThinkStation-P360-Tower:~/LLM4Robot$ python examples/example.py 
2025-01-02 16:49:43,210 Initializing dataset RearrangeDataset-v0
2025-01-02 16:49:50,418 initializing sim RearrangeSim-v0
Traceback (most recent call last):
  File "/home/lqx/LLM4Robot/examples/example.py", line 31, in <module>
    example()
  File "/home/lqx/LLM4Robot/examples/example.py", line 15, in example
    with gym.make("HabitatRenderPick-v0") as env:
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/gym/gym_definitions.py", line 92, in _make_habitat_gym_env
    env = make_gym_from_config(config)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/gym/gym_definitions.py", line 61, in make_gym_from_config
    return make_env_fn(env_class=env_class, config=config)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/utils/env_utils.py", line 33, in make_env_fn
    env = env_class(config=config, dataset=dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/environments.py", line 126, in __init__
    base_env = RLTaskEnv(config=config, dataset=dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/environments.py", line 46, in __init__
    super().__init__(config, dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/env.py", line 382, in __init__
    self._env = Env(config, dataset)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/core/env.py", line 114, in __init__
    self._sim = make_sim(
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/tasks/rearrange/rearrange_sim.py", line 80, in __init__
    super().__init__(config)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/sims/habitat_simulator/habitat_simulator.py", line 292, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat/sims/habitat_simulator/habitat_simulator.py", line 352, in create_sim_config
    sim_config.navmesh_settings = habitat_sim.nav.NavMeshSettings()
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'navmesh_settings'
Exception ignored in: <function Simulator.__del__ at 0x77fbdcefb550>
Traceback (most recent call last):
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 571, in __del__
    self.close(destroy=True)
  File "/home/lqx/mambaforge/envs/llm4robot/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 132, in close
    if not self._initialized:
AttributeError: 'RearrangeSim' object has no attribute '_initialized'
请问如果要对照您对habitatlab的修改，我自己进行修改的话，是按照ks分支进行修改吗？我看您在里面的改动还不少，能麻烦您提供一个要修改哪些内容的提示吗？
